apiVersion: v1
kind: Service
metadata:
  name: cicd-service
  namespace: myapp
spec:
  # type: NodePort
  type: LoadBalancer
  ports:
  - name: http
    port: 5000
    targetPort: 5000
    protocol: TCP
    # nodePort: 30000
  selector:
    app: cicd




