apiVersion: v1
kind: Service
metadata:
  name: cicd-service
spec:
  type: NodePort
  # type: LoadBalancer
  ports:
  - name: http
    port: 80
    targetPort: 5000
    protocol: TCP
    nodePort: 30000
  selector:
    app: cicd




